parameters:
  jormallsms.senderid: '%env(string:JORMALLSMS_SENDERID)%'
  jormallsms.accname: '%env(string:JORMALLSMS_ACCNAME)%'
  jormallsms.accpass: '%env(string:JORMALLSMS_ACCPASS)%'
  jormallsms.sendsmsurl: 'https://josmsservice.com/SMSServices/Clients/Prof/H_SingleSMS_General/SMSService.asmx/SendSMS'
  jormallsms.getbalanceurl: 'https://josmsservice.com/SMS/API/GetBalance'

services:
  _defaults:
    autowire: true
    autoconfigure: true
  Extendy\JormallSmsBundle\Service\JormallSmsService:
    arguments:
      $senderid: '%jormallsms.senderid%'
      $accname: '%jormallsms.accname%'
      $accpass: '%jormallsms.accpass%'
      $sendsmsUrl: '%jormallsms.sendsmsurl%'
      $getbalanceUrl: '%jormallsms.getbalanceurl%'



